insert all
into po.dane values ('abramowitz+stegun','author','Milton Abramowitz and Irene A. Stegun')
into po.dane values ('abramowitz+stegun','title','Handbook of Mathematical Functions with Formulas, Graphs, and Mathematical Tables"')
into po.dane values ('abramowitz+stegun','publisher','Dover')
into po.dane values ('abramowitz+stegun','year','1964')
into po.dane values ('abramowitz+stegun','address','New York')
into po.dane values ('abramowitz+stegun','edition','ninth Dover printing, tenth GPO printing')
into po.dane values ('hicks2001','author','von Hicks, III, Michael')
into po.dane values ('hicks2001','title','Design of a Carbon Fiber Composite Grid Structure for the GLAST Spacecraft Using a Novel Manufacturing Technique')
into po.dane values ('hicks2001','publisher','Stanford Press')
into po.dane values ('hicks2001','year','2001')
into po.dane values ('hicks2001','address','Palo Alto')
into po.dane values ('hicks2001','edition','1st')
into po.dane values ('hicks2001','isbn','0-69-697269-4')
into po.dane values ('King','author','Stephen King')
into po.dane values ('King','title','The Shining')
into po.dane values ('King','publisher','Doubleday')
into po.dane values ('King','year','1977')
into po.dane values ('King','address','United States')
into po.dane values ('King','edition','1st')
into po.dane values ('King','isbn','978-0-385-12167-5')
into po.dane values ('King','pages','447')
into po.dane values ('King1','author','Stephen King')
into po.dane values ('King1','title','The Stand')
into po.dane values ('King1','publisher','Doubleday')
into po.dane values ('King1','year','1978')
into po.dane values ('King1','address','United States')
into po.dane values ('King1','edition','1st')
into po.dane values ('King1','isbn','978-0-385-12168-2')
into po.dane values ('King1','pages','1153')
into po.dane values ('King2','author','Stephen King')
into po.dane values ('King2','title','It')
into po.dane values ('King2','publisher','Viking')
into po.dane values ('King2','year','1986')
into po.dane values ('King2','address','United States')
into po.dane values ('King2','edition','1st')
into po.dane values ('King2','isbn','0-670-81302-8')
into po.dane values ('King2','pages','1138')
into po.dane values ('King3','author','Stephen King')
into po.dane values ('King3','title','Dreamcatcher')
into po.dane values ('King3','publisher','Scribner')
into po.dane values ('King3','year','2001')
into po.dane values ('King3','address','United States')
into po.dane values ('King3','edition','1st')
into po.dane values ('King3','isbn','978-0-7432-1138-3')
into po.dane values ('King3','pages','620')
into po.dane values ('King4','author','Stephen King')
into po.dane values ('King4','title','Cell')
into po.dane values ('King4','publisher','Scribner')
into po.dane values ('King4','year','2006')
into po.dane values ('King4','address','United States')
into po.dane values ('King4','edition','1st')
into po.dane values ('King4','isbn','978-0-7432-9233-7')
into po.dane values ('King4','pages','350')
into po.dane values ('King5','author','Stephen King')
into po.dane values ('King5','title','Desperation')
into po.dane values ('King5','publisher','Viking')
into po.dane values ('King5','year','1996')
into po.dane values ('King5','address','United States')
into po.dane values ('King5','edition','1st')
into po.dane values ('King5','isbn','978-0-670-86836-0')
into po.dane values ('King5','pages','704')
into po.dane values ('King6','author','Stephen King')
into po.dane values ('King6','title','Bag of Bones')
into po.dane values ('King6','publisher','Scribner')
into po.dane values ('King6','year','1998')
into po.dane values ('King6','address','United States')
into po.dane values ('King6','edition','1st')
into po.dane values ('King6','isbn','978-0-684-85350-5')
into po.dane values ('King6','pages','529')
into po.dane values ('Martin','author',' George R.R. Martin')
into po.dane values ('Martin','title','Games os Thrones')
into po.dane values ('Martin','publisher','Bantam Books')
into po.dane values ('Martin','year','1996')
into po.dane values ('Martin','address','United States')
into po.dane values ('Martin','edition','1st')
into po.dane values ('Martin','pages','694')
into po.dane values ('Martin','isbn','0-553-10354-7')
into po.dane values ('Martin','series','A Song of Ice and Fire')
into po.dane values ('Martin1','author',' George R.R. Martin')
into po.dane values ('Martin1','title','A Clash of Kings')
into po.dane values ('Martin1','publisher','Voyager Books')
into po.dane values ('Martin1','year','1998')
into po.dane values ('Martin1','address','United States')
into po.dane values ('Martin1','edition','1st')
into po.dane values ('Martin1','isbn','	0-00-224585-X')
into po.dane values ('Martin1','pages','761')
into po.dane values ('Martin1','series','A Song of Ice and Fire')
into po.dane values ('Martin2','author',' George R.R. Martin')
into po.dane values ('Martin2','title','A Storm of Swords')
into po.dane values ('Martin2','publisher','Voyager Books')
into po.dane values ('Martin2','year','2000')
into po.dane values ('Martin2','address','United States')
into po.dane values ('Martin2','edition','1st')
into po.dane values ('Martin2','isbn','0-553-10663-5')
into po.dane values ('Martin2','pages','973')
into po.dane values ('Martin2','series','A Song of Ice and Fire')
into po.dane values ('Martin3','author',' George R.R. Martin')
into po.dane values ('Martin3','title','A Feast for Crows')
into po.dane values ('Martin3','publisher','Voyager Books')
into po.dane values ('Martin3','year','2005')
into po.dane values ('Martin3','address','United States')
into po.dane values ('Martin3','edition','1st')
into po.dane values ('Martin3','isbn','0-00-224743-7')
into po.dane values ('Martin3','pages','753')
into po.dane values ('Martin3','series','A Song of Ice and Fire')
into po.dane values ('Martin4','author',' George R.R. Martin')
into po.dane values ('Martin4','title','A Dance with Dragons')
into po.dane values ('Martin4','publisher','Voyager Books')
into po.dane values ('Martin4','year','2011')
into po.dane values ('Martin4','address','United States')
into po.dane values ('Martin4','edition','1st')
into po.dane values ('Martin4','isbn','978-0553801477')
into po.dane values ('Martin4','pages','1016')
into po.dane values ('Martin4','series','A Song of Ice and Fire')
into po.dane values ('Martin5','author',' George R.R. Martin')
into po.dane values ('Martin5','title','The Winds of Winter')
into po.dane values ('Martin5','publisher','Voyager Books')
into po.dane values ('Martin5','address','United States')
into po.dane values ('Martin5','series','A Song of Ice and Fire')
into po.dane values ('Martin6','author',' George R.R. Martin')
into po.dane values ('Martin6','title','A Dream of Spring')
into po.dane values ('Martin6','publisher','Voyager Books')
into po.dane values ('Martin6','address','United States')
into po.dane values ('Martin6','series','A Song of Ice and Fire')
into po.dane values ('clarke+g+g+milz','title','Journal of Clinical Medicine')
into po.dane values ('clarke+g+g+milz','publisher','Clarivate Analytics')
into po.dane values ('clarke+g+g+milz','year','2018')
into po.dane values ('clarke+g+g+milz','edition','latest')
into po.dane values ('clarke+g+g+milz','issn','2077-0383')
into po.dane values ('cl+anal','author','Julia Clarke, Thomas Gillingwater, Anthony Graham, Stefan Milz')
into po.dane values ('cl+anal','title','Journal of Anatomy')
into po.dane values ('cl+anal','publisher','Wiley')
into po.dane values ('cl+anal','year','2019')
into po.dane values ('cl+anal','address','Great Britain and Ireland')
into po.dane values ('cl+anal','edition','1st')
into po.dane values ('cl+anal','issn','1469-7580')
into po.dane values ('tolkien','author','J. R. R. Tolkien')
into po.dane values ('tolkien','title','The Lord of the Rings: The Fellowship of the Ring')
into po.dane values ('tolkien','publisher','Allen and Unwin')
into po.dane values ('tolkien','year','1954')
into po.dane values ('tolkien','address','England')
into po.dane values ('tolkien','edition','latest')
into po.dane values ('tolkien','series','Lords of the Rings')
into po.dane values ('tolkien1','author',' J.R.R. Tolkien')
into po.dane values ('tolkien1','title','The Two Towers')
into po.dane values ('tolkien1','publisher','George Allen and Unwin')
into po.dane values ('tolkien1','year','1954')
into po.dane values ('tolkien1','address','United Kingdom')
into po.dane values ('tolkien1','edition','1st')
into po.dane values ('tolkien1','pages','352')
into po.dane values ('tolkien1','series','Lords of the Rings')
into po.dane values ('tolkien2','author',' J.R.R. Tolkien')
into po.dane values ('tolkien2','title','The Return of the King')
into po.dane values ('tolkien2','publisher','George Allen and Unwin')
into po.dane values ('tolkien2','year','1955')
into po.dane values ('tolkien2','address','United Kingdom')
into po.dane values ('tolkien2','edition','1st')
into po.dane values ('tolkien2','pages','416')
into po.dane values ('tolkien1','series','Lords of the Rings')
into po.dane values ('tolkien3','author',' J.R.R. Tolkien')
into po.dane values ('tolkien3','title','The Hobbit, or There and Back Again')
into po.dane values ('tolkien3','publisher','George Allen and Unwin')
into po.dane values ('tolkien3','year','1937')
into po.dane values ('tolkien3','address','United Kingdom')
into po.dane values ('tolkien3','edition','1st')
into po.dane values ('tolkien3','pages','310')
into po.dane values ('rowling','pages','423')
into po.dane values ('rowling','author','J. K. Rowling')
into po.dane values ('rowling','title','Harry Potter and the Philosopher Stone')
into po.dane values ('rowling','publisher','Bloomsbury')
into po.dane values ('rowling','year','1997')
into po.dane values ('rowling','address','United Kingdom')
into po.dane values ('rowling','edition','1st')
into po.dane values ('rowling','pages','223')
into po.dane values ('rowling','isbn','0-7475-3269-9')
into po.dane values ('rowling','series','Harry Potter')
into po.dane values ('rowling1','author',' J.K. Rowling')
into po.dane values ('rowling1','title','Harry Potter and the Chamber of Secrets')
into po.dane values ('rowling1','publisher','Bloomsbury')
into po.dane values ('rowling1','year','1998')
into po.dane values ('rowling1','address','United Kingdom')
into po.dane values ('rowling1','edition','1st')
into po.dane values ('rowling1','isbn','0-7475-3849-2')
into po.dane values ('rowling1','pages','251')
into po.dane values ('rowling1','series','Harry Potter')
into po.dane values ('rowling2','author',' J.K. Rowling')
into po.dane values ('rowling2','title','Harry Potter and the Prisoner of Azkaban')
into po.dane values ('rowling2','publisher','Bloomsbury')
into po.dane values ('rowling2','year','1999')
into po.dane values ('rowling2','address','United Kingdom')
into po.dane values ('rowling2','edition','1st')
into po.dane values ('rowling2','isbn','0-7475-4215-5')
into po.dane values ('rowling2','pages','317')
into po.dane values ('rowling2','series','Harry Potter')
into po.dane values ('rowling3','author',' J.K. Rowling')
into po.dane values ('rowling3','title','Harry Potter and the Goblet of Fire')
into po.dane values ('rowling3','publisher','Bloomsbury')
into po.dane values ('rowling3','year','2000')
into po.dane values ('rowling3','address','United Kingdom')
into po.dane values ('rowling3','edition','1st')
into po.dane values ('rowling3','isbn','0-7475-4624-X')
into po.dane values ('rowling3','pages','636')
into po.dane values ('rowling3','series','Harry Potter')
into po.dane values ('rowling4','author',' J.K. Rowling')
into po.dane values ('rowling4','title','Harry Potter and the Order of the Phoenix')
into po.dane values ('rowling4','publisher','Bloomsbury')
into po.dane values ('rowling4','year','2003')
into po.dane values ('rowling4','address','United Kingdom')
into po.dane values ('rowling4','edition','1st')
into po.dane values ('rowling4','isbn','0-7475-5100-6')
into po.dane values ('rowling4','pages','766')
into po.dane values ('rowling4','series','Harry Potter')
into po.dane values ('rowling5','author',' J.K. Rowling')
into po.dane values ('rowling5','title','Harry Potter and the Half-Blood Prince')
into po.dane values ('rowling5','publisher','Bloomsbury')
into po.dane values ('rowling5','year','2005')
into po.dane values ('rowling5','address','United Kingdom')
into po.dane values ('rowling5','edition','1st')
into po.dane values ('rowling5','isbn','0-7475-8108-8')
into po.dane values ('rowling5','pages','607')
into po.dane values ('rowling5','series','Harry Potter')
into po.dane values ('rowling6','author',' J.K. Rowling')
into po.dane values ('rowling6','title','Harry Potter and the Deathly Hallows')
into po.dane values ('rowling6','publisher','Bloomsbury')
into po.dane values ('rowling6','year','2007')
into po.dane values ('rowling6','address','United Kingdom')
into po.dane values ('rowling6','edition','1st')
into po.dane values ('rowling6','isbn','0-545-01022-5')
into po.dane values ('rowling6','pages','607')
into po.dane values ('rowling6','series','Harry Potter')
into po.dane values ('texas','title','LM358P')
into po.dane values ('texas','organization','Texas Instruments')
into po.dane values ('texas1','title','LM134/LM234/LM334')
into po.dane values ('texas1','organization','Texas Instruments')
into po.dane values ('texas2','title','LM2596')
into po.dane values ('texas2','organization','Texas Instruments')
into po.dane values ('reiman','title','A Starving Man Helping Another Starving Man')
into po.dane values ('reiman','author','Julien Saint Reiman')
into po.dane values ('reiman','school','Columbia University')
into po.dane values ('reiman','year','2018')
into po.dane values ('reiman','type','History')
into po.dane values ('ak-smith','title','Refugees and theatre: an exploration of the basis of self-representation')
into po.dane values ('ak-smith','author','Anna Knowles-Smith')
into po.dane values ('ak-smith','school','University College London')
into po.dane values ('ak-smith','year','2017')
into po.dane values ('ak-smith','type','Geography')
into po.dane values ('jmartindell','title','DCDN: Distributed content delivery for the modern web')
into po.dane values ('jmartindell','author','Nick J. Martindell')
into po.dane values ('jmartindell','school','University of Washington')
into po.dane values ('jmartindell','year','2014')
into po.dane values ('jmartindell','type','Computer Science and Engineering')
into po.dane values ('sloane','author','A. Sloane')
into po.dane values ('sloane','title','The dissolving self: Dementia and identity in philosophical theology')
into po.dane values ('sloane','note','Unpublished manuscript. Bible and Theology Faculty, Morling College.')
into po.dane values ('krueger+colombetti','author','J. Krueger, G. Colombetti')
into po.dane values ('krueger+colombetti','title','Affective affordances and psychopathology')
into po.dane values ('krueger+colombetti','note','Unpublished manuscript. Downloaded from academic.edu, University of Exeter.')
into po.dane values ('mitchell','author','S. D. Mitchell')
into po.dane values ('mitchell','title','The import of uncertainty')
into po.dane values ('mitchell','note','Retrieved from http://philsci-archive.pitt.edu/archive/0000162/')
into po.dane values ('Sapkowski','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski','title','Wiedźmin')
into po.dane values ('Sapkowski','publisher','Reporter')
into po.dane values ('Sapkowski','year','1990')
into po.dane values ('Sapkowski','address','Warszawa')
into po.dane values ('Sapkowski','edition','1st')
into po.dane values ('Sapkowski','isbn','83-85189-01-7')
into po.dane values ('Sapkowski1','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski1','title','Miecz przeznaczenia')
into po.dane values ('Sapkowski1','publisher','superNOWA')
into po.dane values ('Sapkowski1','year','1992')
into po.dane values ('Sapkowski1','address','Warszawa')
into po.dane values ('Sapkowski1','edition','1st')
into po.dane values ('Sapkowski1','isbn','83-7054-037-6')
into po.dane values ('Sapkowski2','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski2','title','Ostatnie życzenie')
into po.dane values ('Sapkowski2','publisher','superNOWA')
into po.dane values ('Sapkowski2','year','1993')
into po.dane values ('Sapkowski2','address','Warszawa')
into po.dane values ('Sapkowski2','edition','1st')
into po.dane values ('Sapkowski2','isbn','83-7054-061-9')
into po.dane values ('Sapkowski3','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski3','title','Coś się kończy, coś się zaczyna')
into po.dane values ('Sapkowski3','publisher','superNOWA')
into po.dane values ('Sapkowski3','year','2000')
into po.dane values ('Sapkowski3','address','Warszawa')
into po.dane values ('Sapkowski3','edition','1st')
into po.dane values ('Sapkowski4','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski4','title','Opowieści o wiedźminie, tom 1')
into po.dane values ('Sapkowski4','publisher','Libros')
into po.dane values ('Sapkowski4','year','2002')
into po.dane values ('Sapkowski4','address','Warszawa')
into po.dane values ('Sapkowski4','edition','1st')
into po.dane values ('Sapkowski5','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski5','title','Opowieści o wiedźminie, tom 2')
into po.dane values ('Sapkowski5','publisher','Libros')
into po.dane values ('Sapkowski5','year','2002')
into po.dane values ('Sapkowski5','address','Warszawa')
into po.dane values ('Sapkowski5','edition','1st')
into po.dane values ('Sapkowski6','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski6','title','Maladie i inne opowiadania')
into po.dane values ('Sapkowski6','publisher','superNOWA')
into po.dane values ('Sapkowski6','year','2012')
into po.dane values ('Sapkowski6','address','Warszawa')
into po.dane values ('Sapkowski6','edition','1st')
into po.dane values ('Sapkowski7','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski7','title','Krew elfów')
into po.dane values ('Sapkowski7','publisher','superNOWA')
into po.dane values ('Sapkowski7','year','1994')
into po.dane values ('Sapkowski7','address','Warszawa')
into po.dane values ('Sapkowski7','edition','1st')
into po.dane values ('Sapkowski7','series','Saga o wiedźminie')
into po.dane values ('Sapkowski8','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski8','title','Czas pogardy')
into po.dane values ('Sapkowski8','publisher','superNOWA')
into po.dane values ('Sapkowski8','year','1995')
into po.dane values ('Sapkowski8','address','Warszawa')
into po.dane values ('Sapkowski8','edition','1st')
into po.dane values ('Sapkowski8','series','Saga o wiedźminie')
into po.dane values ('Sapkowski9','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski9','title','Chrzest ognia')
into po.dane values ('Sapkowski9','publisher','superNOWA')
into po.dane values ('Sapkowski9','year','1996')
into po.dane values ('Sapkowski9','address','Warszawa')
into po.dane values ('Sapkowski9','edition','1st')
into po.dane values ('Sapkowski9','series','Saga o wiedźminie')
into po.dane values ('Sapkowski10','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski10','title','Wieża Jaskółki')
into po.dane values ('Sapkowski10','publisher','superNOWA')
into po.dane values ('Sapkowski10','year','1997')
into po.dane values ('Sapkowski10','address','Warszawa')
into po.dane values ('Sapkowski10','edition','1st')
into po.dane values ('Sapkowski10','series','Saga o wiedźminie')
into po.dane values ('Sapkowski11','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski11','title','Pani Jeziora')
into po.dane values ('Sapkowski11','publisher','superNOWA')
into po.dane values ('Sapkowski11','year','1999')
into po.dane values ('Sapkowski11','address','Warszawa')
into po.dane values ('Sapkowski11','edition','1st')
into po.dane values ('Sapkowski11','series','Saga o wiedźminie')
into po.dane values ('Sapkowski12','author','Andrzej Sapkowski')
into po.dane values ('Sapkowski12','title','Sezon burz')
into po.dane values ('Sapkowski12','publisher','superNOWA')
into po.dane values ('Sapkowski12','year','2013')
into po.dane values ('Sapkowski12','address','Warszawa')
into po.dane values ('Sapkowski12','edition','1st')
into po.dane values ('Sapkowski12','isbn','978-83-7578-059-8')
select *  from dual;
               
