insert all
into po.literatura values ('abramowitz+stegun','book')
into po.literatura values ('hicks2001','book')
into po.literatura values ('King','book')
into po.literatura values ('Martin','book')
select *  from dual;

insert all
into po.dane values ('abramowitz+stegun','author','Milton Abramowitz and Irene A. Stegun')
into po.dane values ('abramowitz+stegun','title','Handbook of Mathematical Functions with Formulas, Graphs, and Mathematical Tables"')
into po.dane values ('abramowitz+stegun','publisher','Dover')
into po.dane values ('abramowitz+stegun','year','1964')
into po.dane values ('abramowitz+stegun','address','New York')
into po.dane values ('abramowitz+stegun','edition','ninth Dover printing, tenth GPO printing')
into po.dane values ('hicks2001','author','von Hicks, III, Michael')
into po.dane values ('hicks2001','title','Design of a Carbon Fiber Composite Grid Structure for the GLAST Spacecraft Using a Novel Manufacturing Technique')
into po.dane values ('hicks2001','publisher','Stanford Press')
into po.dane values ('hicks2001','year','2001')
into po.dane values ('hicks2001','address','Palo Alto')
into po.dane values ('hicks2001','edition','1st')
into po.dane values ('hicks2001','isbn','0-69-697269-4')
into po.dane values ('King','author','Stephen King')
into po.dane values ('King','title','The Shining')
into po.dane values ('King','publisher','Doubleday')
into po.dane values ('King','year','1977')
into po.dane values ('King','address','United States')
into po.dane values ('King','edition','1st')
into po.dane values ('King','isbn','978-0-385-12167-5')
into po.dane values ('Martin','author',' George R.R. Martin')
into po.dane values ('Martin','title','A Song of Ice and Fire')
into po.dane values ('Martin','publisher','Bantam Books')
into po.dane values ('Martin','year','1996')
into po.dane values ('Martin','address','United States')
into po.dane values ('Martin','edition','1st')
select *  from dual;

insert all
into po.slownik values ('Article','Journal',1)
into po.slownik values ('Article','Volume',0)
into po.slownik values ('Book','Publisher',1)
into po.slownik values ('Book','Year',1)
into po.slownik values ('Booklet','Title',1)
into po.slownik values ('Conference','Author',1)
into po.slownik values ('Conference','Title',1)
into po.slownik values ('Conference','Booktitle',1)
into po.slownik values ('Conference','Year',1)
into po.slownik values ('Inbook','Author/Editor',1)
into po.slownik values ('Inbook','Title',1)
into po.slownik values ('Inbook','Chapter/Pages',1)
into po.slownik values ('Inbook','Publisher',1)
into po.slownik values ('Inbook','Year',1)
into po.slownik values ('Incollection','Author',1)
into po.slownik values ('Incollection','Title',1)
into po.slownik values ('Incollection','Booktitle',1)
into po.slownik values ('Incollection','Publisher',1)
into po.slownik values ('Incollection','Year',1)
into po.slownik values ('Inproceedings','Author',1)
into po.slownik values ('Inproceedings','Title',1)
into po.slownik values ('Inproceedings','Booktitle',1)
into po.slownik values ('Inproceedings','Year',1)
into po.slownik values ('Manual','Title',1)
into po.slownik values ('Masterthesis','Author',1)
into po.slownik values ('Masterthesis','Title',1)
into po.slownik values ('Masterthesis','School',1)
into po.slownik values ('Masterthesis','Year',1)
into po.slownik values ('Phdthesis','Author',1)
into po.slownik values ('Phdthesis','Title',1)
into po.slownik values ('Phdthesis','School',1)
into po.slownik values ('Phdthesis','Year',1)
into po.slownik values ('Techreport','Author',1)
into po.slownik values ('Techreport','Title',1)
into po.slownik values ('Techreport','Institution',1)
into po.slownik values ('Techreport','Year',1)
into po.slownik values ('Unpublished','Title',1)
into po.slownik values ('Unpublished','Author',1)
into po.slownik values ('Unpublished','Note',1)
select *  from dual;
