insert all
into po.literatura values ('abramowitz+stegun','book')
into po.literatura values ('hicks2001','book')
into po.literatura values ('King','book')
into po.literatura values ('Martin','book')
into po.literatura values ('clarke+g+g+milz','article')
into po.literatura values ('cl+anal','article')
into po.literatura values ('tolkien','book')
into po.literatura values ('rowling','book')
into po.literatura values ('texas','manual')
into po.literatura values ('reiman','phdthesis')
into po.literatura values ('ak-smith','phdthesis')
into po.literatura values ('jmartindell','phdthesis')
into hr.literatura values ('sloane','Unpublished')
into hr.literatura values ('krueger+colombetti','Unpublished')
into hr.literatura values ('mitchell','Unpublished')
select *  from dual;
