insert all
into po.dane values ('abramowitz+stegun','author','Milton Abramowitz and Irene A. Stegun')
into po.dane values ('abramowitz+stegun','title','Handbook of Mathematical Functions with Formulas, Graphs, and Mathematical Tables"')
into po.dane values ('abramowitz+stegun','publisher','Dover')
into po.dane values ('abramowitz+stegun','year','1964')
into po.dane values ('abramowitz+stegun','address','New York')
into po.dane values ('abramowitz+stegun','edition','ninth Dover printing, tenth GPO printing')
into po.dane values ('hicks2001','author','von Hicks, III, Michael')
into po.dane values ('hicks2001','title','Design of a Carbon Fiber Composite Grid Structure for the GLAST Spacecraft Using a Novel Manufacturing Technique')
into po.dane values ('hicks2001','publisher','Stanford Press')
into po.dane values ('hicks2001','year','2001')
into po.dane values ('hicks2001','address','Palo Alto')
into po.dane values ('hicks2001','edition','1st')
into po.dane values ('hicks2001','isbn','0-69-697269-4')
into po.dane values ('King','author','Stephen King')
into po.dane values ('King','title','The Shining')
into po.dane values ('King','publisher','Doubleday')
into po.dane values ('King','year','1977')
into po.dane values ('King','address','United States')
into po.dane values ('King','edition','1st')
into po.dane values ('King','isbn','978-0-385-12167-5')
into po.dane values ('Martin','author',' George R.R. Martin')
into po.dane values ('Martin','title','A Song of Ice and Fire')
into po.dane values ('Martin','publisher','Bantam Books')
into po.dane values ('Martin','year','1996')
into po.dane values ('Martin','address','United States')
into po.dane values ('Martin','edition','1st')
into po.dane values ('clarke+g+g+milz','title','Journal of Clinical Medicine')
into po.dane values ('clarke+g+g+milz','publisher','Clarivate Analytics')
into po.dane values ('clarke+g+g+milz','year','2018')
into po.dane values ('clarke+g+g+milz','edition','latest')
into po.dane values ('clarke+g+g+milz','issn','2077-0383')
into po.dane values ('cl+anal','author','Julia Clarke, Thomas Gillingwater, Anthony Graham, Stefan Milz')
into po.dane values ('cl+anal','title','Journal of Anatomy')
into po.dane values ('cl+anal','publisher','Wiley')
into po.dane values ('cl+anal','year','2019')
into po.dane values ('cl+anal','address','Great Britain and Ireland')
into po.dane values ('cl+anal','edition','1st')
into po.dane values ('cl+anal','issn','1469-7580')
into po.dane values ('tolkien','author','J. R. R. Tolkien')
into po.dane values ('tolkien','title','The Lord of the Rings: The Fellowship of the Ring')
into po.dane values ('tolkien','publisher','Allen and Unwin')
into po.dane values ('tolkien','year','1954')
into po.dane values ('tolkien','address','England')
into po.dane values ('tolkien','edition','latest')
into po.dane values ('rowling','pages','423')
into po.dane values ('rowling','author','J. K. Rowling')
into po.dane values ('rowling','title','Harry Potter and the Philosopher Stone')
into po.dane values ('rowling','publisher','Bloomsbury')
into po.dane values ('rowling','year','1997')
into po.dane values ('rowling','address','United Kingdom')
into po.dane values ('rowling','edition','1st')
into po.dane values ('rowling','pages','223')
into po.dane values ('rowling','isbn','0-7475-3269-9')
into po.dane values ('King','pages','447')
into po.dane values ('Martin','pages','694')
into po.dane values ('Martin','series','Games os Thrones')
into po.dane values ('tolkien','series','Lords of the Rings')
into po.dane values ('rowling','series','Harry Potter')
into po.dane values ('texas','title','LM358P')
into po.dane values ('texas','organization','Texas Instruments')
into po.dane values ('texas1','title','LM134/LM234/LM334')
into po.dane values ('texas1','organization','Texas Instruments')
into po.dane values ('texas2','title','LM2596')
into po.dane values ('texas2','organization','Texas Instruments')
into po.dane values ('reiman','title','A Starving Man Helping Another Starving Man')
into po.dane values ('reiman','author','Julien Saint Reiman')
into po.dane values ('reiman','school','Columbia University')
into po.dane values ('reiman','year','2018')
into po.dane values ('reiman','type','History')
into po.dane values ('ak-smith','title','Refugees and theatre: an exploration of the basis of self-representation')
into po.dane values ('ak-smith','author','Anna Knowles-Smith')
into po.dane values ('ak-smith','school','University College London')
into po.dane values ('ak-smith','year','2017')
into po.dane values ('ak-smith','type','Geography')
into po.dane values ('jmartindell','title','DCDN: Distributed content delivery for the modern web')
into po.dane values ('jmartindell','author','Nick J. Martindell')
into po.dane values ('jmartindell','school','University of Washington')
into po.dane values ('jmartindell','year','2014')
into po.dane values ('jmartindell','type','Computer Science and Engineering')
into po.dane values ('sloane','author','A. Sloane')
into po.dane values ('sloane','title','The dissolving self: Dementia and identity in philosophical theology')
into po.dane values ('sloane','note','Unpublished manuscript. Bible and Theology Faculty, Morling College.')
into po.dane values ('krueger+colombetti','author','J. Krueger, G. Colombetti')
into po.dane values ('krueger+colombetti','title','Affective affordances and psychopathology')
into po.dane values ('krueger+colombetti','note','Unpublished manuscript. Downloaded from academic.edu, University of Exeter.')
into po.dane values ('mitchell','author','S. D. Mitchell')
into po.dane values ('mitchell','title','The import of uncertainty')
into po.dane values ('mitchell','note','Retrieved from http://philsci-archive.pitt.edu/archive/0000162/')
select *  from dual;
               
