insert all
into po.literatura values ('abramowitz+stegun','book')
into po.literatura values ('hicks2001','book')
select *  from dual;

insert all
into po.dane values ('abramowitz+stegun','author','Milton Abramowitz and Irene A. Stegun')
into po.dane values ('abramowitz+stegun','title','Handbook of Mathematical Functions with Formulas, Graphs, and Mathematical Tables"')
into po.dane values ('abramowitz+stegun','publisher','Dover')
into po.dane values ('abramowitz+stegun','year','1964')
into po.dane values ('abramowitz+stegun','address','New York')
into po.dane values ('abramowitz+stegun','edition','ninth Dover printing, tenth GPO printing')
into po.dane values ('hicks2001','author','von Hicks, III, Michael')
into po.dane values ('hicks2001','title','Design of a Carbon Fiber Composite Grid Structure for the GLAST Spacecraft Using a Novel Manufacturing Technique')
into po.dane values ('hicks2001','publisher','Stanford Press')
into po.dane values ('hicks2001','year','2001')
into po.dane values ('hicks2001','address','Palo Alto')
into po.dane values ('hicks2001','edition','1st')
into po.dane values ('hicks2001','isbn','0-69-697269-4')
select *  from dual;

insert all
into po.slownik values ('Article','Journal',1)
into po.slownik values ('Article','Volume',0)
into po.slownik values ('Book','Publisher',1)
into po.slownik values ('Book','Year',1)
into po.slownik values ('Booklet','Title',1)
into po.slownik values ('Conference','Author',1)
into po.slownik values ('Conference','Title',1)
into po.slownik values ('Conference','Booktitle',1)
into po.slownik values ('Conference','Year',1)
into po.slownik values ('Inbook','Author/Editor',1)
into po.slownik values ('Inbook','Title',1)
into po.slownik values ('Inbook','Chapter/Pages',1)
into po.slownik values ('Inbook','Publisher',1)
into po.slownik values ('Inbook','Year',1)
into po.slownik values ('Incollection','Author',1)
into po.slownik values ('Incollection','Title',1)
into po.slownik values ('Incollection','Booktitle',1)
into po.slownik values ('Incollection','Publisher',1)
into po.slownik values ('Incollection','Year',1)
into po.slownik values ('Inproceedings','Author',1)
into po.slownik values ('Inproceedings','Title',1)
into po.slownik values ('Inproceedings','Booktitle',1)
into po.slownik values ('Inproceedings','Year',1)
select *  from dual;
